### ISSUE TITLE
performBatchUpdates bug

### ISSUE THREAD

**Issue by scottphc** [DenHeadless/DTCollectionViewManager#26] opened 2017-07-11 07:51 UTC
Random crashes may happen because this issue:
https://openradar.appspot.com/28167779

I use DTCollectionViewManager with Realm, it threw this error:

```
Fatal Exception: RLMException
Index 6 is out of bounds (must be less than 0)
```

**Comment by DenHeadless** [comment] 2017-07-11 17:59
I'm not convinced that those two issues are connected. That error message from Realm is very cryptic, index less than zero? Looks like this might be Realm bug as well.

Did you try looking into related issues on realm-cocoa repo?

https://github.com/realm/realm-cocoa/issues/4248
https://github.com/realm/realm-cocoa/issues/4499

**Comment by scottphc** [comment] 2017-07-12 03:46
I confirmed this is not a realm issue. I use reloadData instead of performBatchUpdates, and then everything will be fine.

The error from `CollectionViewUpdater.swift:func storageDidPerformUpdate:collectionView?.performBatchUpdates, and it will tigger collectionView:cellForItemAt > storage.item(at: indexPath) > RealmStorage.swift:func item:(sections[indexPath.section] as? ItemAtIndexPathRetrievable)?.itemAt(indexPath) > RealmSection.swift:func itemAt:results[indexPath.item]`

**Comment by DenHeadless** [comment] 2017-07-12 06:23
Did you manage to dig out the reason why this is happening? Any suggestions on how to reproduce/fix this?

**Comment by scottphc** [comment] 2017-07-12 07:07
This is a UICollectionView bug, and the reproduced way you can see the link I provided.

I don't have any easily ways to fix this. Perhaps have some workarounds to skip Apple's bug, but need more testing.

Now I use reloadData instead of performBatchUpdates, but it will lose insert/update/delete animation.

**Comment by DenHeadless** [comment] 2017-07-12 11:15
I created a separate issue to track for this bug, since it is not connected to Realm and is more generic - #27.

I will close this issue for now. If you have any Realm-related workarounds/information for this issue, please reopen this issue. If you have ideas how to solve more generic problem, please post them in #27.

Thanks!

**Closed by DenHeadless** 2017-07-12 11:15 UTC
Labels: question, waiting for feedback
